CREATE DATABASE sql_task;

USE sql_task;

CREATE TABLE Employee(
	EMPLOYEE_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    SALARY DECIMAL(10,2),
    JOINING_DATE DATETIME,
    DEPARTMENT VARCHAR(50)
);

ALTER TABLE Employee MODIFY JOINING_DATE DATE;

INSERT INTO Employee VALUES
(1, 'Venkatesh', 'S', 100000, '2015-08-28', 'BANKING'),
(2, 'Ragavi', 'P', 75000, '2015-08-28', 'BUSINESS'),
(3, 'Gopinath', 'C', 50000, '2016-03-02', 'PHARMA'),
(4, 'Dinesh', 'G', 50000, '2016-03-02', 'INSURANCE'),
(5, 'Saibabu', 'E', 40000, '2017-07-08', 'SOFTWARE'),
(6, 'Hasan', 'S', 29000, '2017-07-08', 'MANUFACTURING'),
(7, 'Divya', 'P', 33000, '2017-07-08', 'HEALTHCARE'),
(8, 'Aravindan', 'R', 40000, '2017-07-08', 'HEALTHCARE'),
(9, 'Sathish', 'MD', 45000, '2016-03-02', 'AUTOMOBILE'),
(10, 'Prasanth', 'PKP', 34000, '2016-03-02', 'INSURANCE'),
(11, 'Vijay', 'R', 25684, '2016-03-02', 'BUSINESS'),
(12, 'Sivakumar', 'K', 54789, '2016-03-02', 'SOFTWARE');

CREATE TABLE Incentives (
    EMPLOYEE_REF_ID INT,
    INCENTIVE_DATE DATE,
    INCENTIVE_AMOUNT DECIMAL(10,2),
    FOREIGN KEY (EMPLOYEE_REF_ID) REFERENCES Employee(EMPLOYEE_ID)
);

insert into Incentives values
(1,'2016-02-01',5000),
(2, '2016-02-01', 3000),
(3, '2017-02-01', 4000),
(1, '2017-01-01', 4500),
(2, '2017-01-01', 3500);

SELECT * FROM Employee;

SELECT FIRST_NAME, LAST_NAME FROM Employee;

SELECT FIRST_NAME AS "Employee Name" FROM Employee;

SELECT UPPER(FIRST_NAME) FROM Employee;

SELECT LOWER(FIRST_NAME) FROM Employee;

SELECT DISTINCT DEPARTMENT FROM Employee;

SELECT SUBSTRING(FIRST_NAME, 1, 3) FROM Employee;

SELECT INSTR(FIRST_NAME,'a') FROM Employee WHERE FIRST_NAME = 'Ragavi';

SELECT RTRIM(FIRST_NAME) FROM Employee;

SELECT LTRIM(FIRST_NAME) FROM Employee;

SELECT LENGTH(FIRST_NAME) FROM Employee;

SELECT REPLACE(FIRST_NAME, 'a', '$') FROM Employee;

SELECT CONCAT(FIRST_NAME, '_', LAST_NAME) FROM Employee;

SELECT FIRST_NAME, 
	YEAR(JOINING_DATE) AS Join_Year,
	MONTH(JOINING_DATE) AS Join_Month,
	day(JOINING_DATE) AS Join_Day
	FROM Employee;

SELECT * FROM Employee ORDER BY FIRST_NAME ASC;

SELECT * FROM Employee ORDER BY FIRST_NAME DESC;

SELECT * FROM Employee ORDER BY FIRST_NAME ASC, SALARY DESC;

SELECT * FROM Employee WHERE FIRST_NAME = 'Dinesh';

SELECT * FROM Employee WHERE FIRST_NAME IN ('Dinesh', 'Roy');

SELECT * FROM Employee WHERE FIRST_NAME NOT IN ('Dinesh', 'Roy');

SELECT * FROM Employee 
WHERE FIRST_NAME LIKE 's%';

SELECT * FROM Employee 
WHERE FIRST_NAME LIKE '%v%';

SELECT * FROM Employee 
WHERE FIRST_NAME LIKE '%n';

SELECT * FROM Employee 
WHERE FIRST_NAME LIKE '___n';

SELECT * FROM Employee 
WHERE FIRST_NAME LIKE 'J___';

SELECT * FROM Employee 
WHERE SALARY > 60000;

SELECT * FROM Employee 
WHERE SALARY < 80000;

SELECT * FROM Employee 
WHERE SALARY BETWEEN 50000 AND 80000;

SELECT * FROM Employee 
WHERE FIRST_NAME IN ('Venkatesh', 'Ragavi');

SELECT * FROM Employee 
WHERE year(JOINING_DATE) = 2015;

SELECT * FROM Employee 
WHERE month(JOINING_DATE) = 1;

SELECT * FROM Employee 
WHERE JOINING_DATE > '2016-01-31';

SELECT JOINING_DATE,
	CAST(JOINING_DATE AS time) as JoiningTime
FROM Employee;

SELECT JOINING_DATE, 
	DATE_FORMAT(JOINING_DATE, '%Y-%m-%d %H:%i:%s:%f')
FROM Employee;

SELECT e.EMPLOYEE_ID, 
	DATEDIFF(i.INCENTIVE_DATE, e.JOINING_DATE)
	FROM Employee e 
	JOIN Incentives i ON e.EMPLOYEE_ID = i.EMPLOYEE_REF_ID;
    
SELECT NOW(); SELECT CURRENT_TIMESTAMP;

SELECT * FROM Employee
WHERE LAST_NAME LIKE '%\%%' ESCAPE '\\';

SELECT REGEXP_REPLACE(LAST_NAME, '[!@#$%^&*()]', ' ')
FROM Employee;

SELECT DEPARTMENT, SUM(SALARY) as Total_Salary 
FROM Employee 
GROUP BY DEPARTMENT;

SELECT DEPARTMENT, SUM(SALARY) as Total_Salary 
FROM Employee 
GROUP BY DEPARTMENT 
ORDER BY Total_Salary DESC;

SELECT DEPARTMENT, 
COUNT(*) as Employee_Count,
SUM(SALARY) as Total_Salary 
FROM Employee 
GROUP BY DEPARTMENT 
ORDER BY Total_Salary DESC;

SELECT DEPARTMENT, AVG(SALARY) as Avg_Salary 
FROM Employee 
GROUP BY DEPARTMENT 
ORDER BY Avg_Salary ASC;

SELECT DEPARTMENT, MAX(SALARY) as Max_Salary 
FROM Employee 
GROUP BY DEPARTMENT 
ORDER BY Max_Salary ASC;

SELECT DEPARTMENT, MIN(SALARY) as Min_Salary 
FROM Employee 
GROUP BY DEPARTMENT 
ORDER BY Min_Salary ASC;

SELECT YEAR(JOINING_DATE) as Year, 
MONTH(JOINING_DATE) as Month,
COUNT(*) as Employee_Count 
FROM Employee 
GROUP BY Year, Month;

SELECT DEPARTMENT, SUM(SALARY) as Total_Salary 
FROM Employee 
GROUP BY DEPARTMENT 
HAVING SUM(SALARY) > 80000 
ORDER BY Total_Salary DESC;

SELECT e.FIRST_NAME, i.INCENTIVE_AMOUNT 
FROM Employee e 
INNER JOIN Incentives i ON e.EMPLOYEE_ID = i.EMPLOYEE_REF_ID;

SELECT e.FIRST_NAME, i.INCENTIVE_AMOUNT 
FROM Employee e 
INNER JOIN Incentives i ON e.EMPLOYEE_ID = i.EMPLOYEE_REF_ID 
WHERE i.INCENTIVE_AMOUNT > 3000;

SELECT e.FIRST_NAME, i.INCENTIVE_AMOUNT 
FROM Employee e 
LEFT JOIN Incentives i ON e.EMPLOYEE_ID = i.EMPLOYEE_REF_ID;

SELECT e.FIRST_NAME, 
COALESCE(i.INCENTIVE_AMOUNT, 0) as INCENTIVE_AMOUNT 
FROM Employee e 
LEFT JOIN Incentives i ON e.EMPLOYEE_ID = i.EMPLOYEE_REF_ID;

SELECT e.FIRST_NAME, i.INCENTIVE_AMOUNT 
FROM Employee e 
LEFT JOIN Incentives i ON e.EMPLOYEE_ID = i.EMPLOYEE_REF_ID 
WHERE i.INCENTIVE_AMOUNT IS NOT NULL;

SELECT e.FIRST_NAME,
(SELECT MAX(INCENTIVE_AMOUNT) 
 FROM Incentives i 
 WHERE i.EMPLOYEE_REF_ID = e.EMPLOYEE_ID) as Max_Incentive
FROM Employee e;

SELECT salary
FROM Employee
ORDER BY salary DESC
LIMIT 2;

SELECT salary
FROM Employee
ORDER BY salary DESC
LIMIT 7; -- for eg here 7 is the Nth number

SELECT salary
FROM Employee
ORDER BY salary DESC
LIMIT 1 OFFSET 6; -- for eg here 6 is the Nth number

SELECT FIRST_NAME FROM Employee 
UNION 
SELECT LAST_NAME FROM Employee;

SELECT * FROM Employee e 
WHERE EXISTS (
    SELECT * FROM Incentives i 
    WHERE i.EMPLOYEE_REF_ID = e.EMPLOYEE_ID
);

SELECT e.EMPLOYEE_ID, e.FIRST_NAME
FROM Employee e
INNER JOIN Incentives i ON e.EMPLOYEE_ID = i.EMPLOYEE_REF_ID;

SELECT e.EMPLOYEE_ID 
FROM Employee e 
LEFT JOIN Incentives i ON e.EMPLOYEE_ID = i.EMPLOYEE_REF_ID 
WHERE i.EMPLOYEE_REF_ID IS NULL;

SELECT FIRST_NAME,
CASE 
    WHEN FIRST_NAME = 'Venkatesh' THEN SALARY * 0.20
    WHEN FIRST_NAME like 'Gopi%' THEN SALARY * 0.10
    ELSE SALARY * 0.15
END as Calculated_Salary,SALARY
FROM Employee;

SELECT 
CASE DEPARTMENT
    WHEN 'BANKING' THEN 'Bank Dept'
    WHEN 'INSURANCE' THEN 'Insurance Dept'
    WHEN 'PHARMA' THEN 'Pharma Dept'
    ELSE DEPARTMENT
END as Dept_Name
FROM Employee;

DELETE FROM Employee 
WHERE EMPLOYEE_ID IN (
    SELECT DISTINCT EMPLOYEE_REF_ID 
    FROM Incentives
);

SELECT * FROM Employee;

INSERT INTO Employee (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT) 
VALUES (13, 'John', 'O''Connor', 50000, '2024-01-01', 'SOFTWARE');


SELECT LAST_NAME
FROM Employee
WHERE LAST_NAME REGEXP '^[0-9]+$';

SELECT e.FIRST_NAME,
i.INCENTIVE_AMOUNT,
RANK() OVER (ORDER BY i.INCENTIVE_AMOUNT DESC) as incentive_rank
FROM Employee e 
JOIN Incentives i ON e.EMPLOYEE_ID = i.EMPLOYEE_REF_ID;

UPDATE Incentives 
SET INCENTIVE_AMOUNT = INCENTIVE_AMOUNT + 1000 
WHERE EMPLOYEE_REF_ID = (
    SELECT EMPLOYEE_ID 
    FROM Employee 
    WHERE FIRST_NAME = 'Dinesh'
);








